create TABLE todo_category(
	ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	CATEGORY VARCHAR(30) NOT NULL
)

CREATE TABLE todo (
    ID INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MODIFIED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(10) NOT NULL,
	CATEGORY_ID INT(6) UNSIGNED NOT NULL,
	FOREIGN KEY (CATEGORY_ID) REFERENCES todo_category (ID) ON DELETE CASCADE
)